// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ' AIzaSyCxjB2lmnQoY2ORtK7FtMSSt8MRZ_iFv28 ',
    appId: '1:400833208514:android:f709dcd92db83fcd0b1b5b',
    messagingSenderId: '400833208514',
    projectId: 'pokemonshinyhunt-ba36c',
    storageBucket: 'com.JonathanSonnen.pokemon_shiny_hunt',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ' AIzaSyCxjB2lmnQoY2ORtK7FtMSSt8MRZ_iFv28 ',
    appId: '1:400833208514:android:f709dcd92db83fcd0b1b5b',
    messagingSenderId: '400833208514 ',
    projectId: 'pokemonshinyhunt-ba36c',
    storageBucket: 'com.JonathanSonnen.pokemon_shiny_hunt',
    iosClientId: '879683392852-033rm5j7vc5spd6frsolbs4g8jqfd7jg.apps.googleusercontent.com', //TODO change
    iosBundleId: 'com.example.authentication', // TODO change
  );

}
